name: Running tests

on:
  pull_request:
    branches: ['develop', 'main']

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Set up yarn
        run: |
          corepack enable
          yarn set version stable
      - name: Install dependencies
        run: yarn install --immutable
      - name: Running tests
        run: yarn test:cov
